src/CMakeLists.txt: do not completely overwrite CMAKE_CXX_FLAGS
causes for hardfloat machine:

/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>